spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ezcolas/app-config-repo
          repos:
            dev:
              pattern:
                - '*/development'
                - '*/staging'
              uri: https://github.com/ezcolas/development/app-config-repo
            staging:
              pattern:
                - '*/qa'
                - '*/production'
              uri: https://github.com/ezcolas/staging/app-config-repo