server:
  port: 8888

spring:
  application:
    name: app-config-repo

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ezcolas/app-config-repo
          username: ezcolas
          password: Miledie9
          force-pull: true # Avoid making your local dirty
          cloneOnStart: true # Clone the repository at Start up